name: Backup RDS to S3
on:
   # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Permite que se ejecute automaticamente Cron
  schedule:
      - cron: '40 1 * * *'
      
jobs:
  backup:
    runs-on: ubuntu-latest
    env:
        filename: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Cambiar a la regiÃ³n correcta

      - name: Dump RDS database
        run: |
          timestamp=$(date +%Y%m%d%H%M%S)
          export filename=DBTEST-$timestamp.sql
          echo "Timestamp: $timestamp"
          echo "Filename: $filename"
          TOKEN=$(aws rds generate-db-auth-token --hostname creditv-db.c7ai7kcko0e9.us-east-1.rds.amazonaws.com --port 3306 --region us-east-1 --username admin)
          mysqldump --host=creditv-db.c7ai7kcko0e9.us-east-1.rds.amazonaws.com --port=3306 --user=admin --password=43YBARqqmz creditv-db > $filename
      - name: Check backup
        run: |
          if [ -f $filename ]; then
            echo "Backup created successfully!"
            pwd
            echo "respaldo: $filename"
            ls -l $filename
          else
            echo "Backup failed!"
          fi
      - name: Upload backup to S3
        run: |
          aws s3 cp $filename s3://frkpruebas/respaldo/
          
