name: Backup RDS to S3

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecutar todos los días a la medianoche

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ AKIAS6ERM7KFCWZSFIRC }}
          aws-secret-access-key: ${{ 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 }}
          aws-region: us-east-1  # Cambiar a la región correcta

      - name: Dump RDS database
        run: |
          TOKEN=$(aws rds generate-db-auth-token --hostname creditv-db.c7ai7kcko0e9.us-east-1.rds.amazonaws.com --port 3306 --region us-east-1 --username admin)
          mysqldump --host=127.0.0.1 --port=3306 --user=admin --password="$TOKEN" creditv-db > backup.sql

      - name: Upload backup to S3
        run: |
          aws s3 cp backup.sql s3://resplado-bd-cerditvtest/Respaldo Bd CrediTV-test/backup.sql
